# Server Config
server:
    port: 7010

spring:
  application:
    name: notification-service

# Spring Config
logging:
  level:
    org:
      springframework:
        security: trace

# App Config
sender:
  email: ${EMAIL_ID}
  passwd: ${EMAIL_PASSWD}

# Eureka Server Config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7030/eureka
    registerWithEureka: true
    fetchRegistry: true