# Server Config
server:
    port: 9191

spring:
    application:
        name: kafka-service
# Eureka Server Config
    kafka:
        producer:
            bootstrap-servers: localhost:9092
        consumer:
            bootstrap-servers: localhost:9092
            group-id: my-cons-group-1